// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UFSEstates.Data;

#nullable disable

namespace UFSEstates.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609223515_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UFSEstates.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Complainant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfComplaint")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Complainant = "Ben",
                            DateOfComplaint = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "There is a leaking pipe near the parking lot of the Library Building.",
                            Service = "Water"
                        },
                        new
                        {
                            Id = 2,
                            Complainant = "Sandy",
                            DateOfComplaint = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The water supply to the pumps adjacent to Revier Hall is currently not functioning.",
                            Service = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Complainant = "Gert",
                            DateOfComplaint = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Computer Science Laboratory has been without electrical power since yesterday.",
                            Service = "Electricity"
                        },
                        new
                        {
                            Id = 4,
                            Complainant = "Dean",
                            DateOfComplaint = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The streetlights near the residential building are malfunctioning.",
                            Service = "Electricity"
                        },
                        new
                        {
                            Id = 5,
                            Complainant = "Merry",
                            DateOfComplaint = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The main hall has not been cleaned after the graduation ceremony.",
                            Service = "Cleaning"
                        },
                        new
                        {
                            Id = 6,
                            Complainant = "Meggy",
                            DateOfComplaint = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The main university road next to the cafeteria is blocked by trees.",
                            Service = "Cleaning"
                        },
                        new
                        {
                            Id = 7,
                            Complainant = "Mofokeng",
                            DateOfComplaint = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All the new sports field showers do not have running water.",
                            Service = "Water"
                        },
                        new
                        {
                            Id = 8,
                            Complainant = "Pule",
                            DateOfComplaint = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The electric sockets in the admin building are not working.",
                            Service = "Electricity"
                        },
                        new
                        {
                            Id = 9,
                            Complainant = "Koena",
                            DateOfComplaint = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The road to the admin building needs repairs because the traffic road signs are no longer visible.",
                            Service = "Roads"
                        },
                        new
                        {
                            Id = 10,
                            Complainant = "Lizzy",
                            DateOfComplaint = new DateTime(2025, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "There are unauthorized people who are using undercover parking near the old lecture hall building.",
                            Service = "Parking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
